
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `PartialProximity`=list(
        `type`="software", 
        `author`="Sebastian Jentschke", 
        `year`=2019, 
        `title`="Partial Proximity", 
        `publisher`="[Computer software]. Retrieved from https://www.jamovi.org/library.html", 
        `url`="https://www.jamovi.org/library.html"))
