
# This file is automatically generated, you probably don't want to edit this

partcorrOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "partcorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            corrvars = NULL,
            ctrlvars = NULL,
            shwSig = TRUE,
            flgSig = FALSE,
            sidSig = "twotailed", ...) {

            super$initialize(
                package='PartialProximity',
                name='partcorr',
                requiresData=TRUE,
                ...)

            private$..corrvars <- jmvcore::OptionVariables$new(
                "corrvars",
                corrvars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ctrlvars <- jmvcore::OptionVariables$new(
                "ctrlvars",
                ctrlvars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..shwSig <- jmvcore::OptionBool$new(
                "shwSig",
                shwSig,
                default=TRUE)
            private$..flgSig <- jmvcore::OptionBool$new(
                "flgSig",
                flgSig,
                default=FALSE)
            private$..sidSig <- jmvcore::OptionList$new(
                "sidSig",
                sidSig,
                options=list(
                    "onetailed",
                    "twotailed"),
                default="twotailed")

            self$.addOption(private$..corrvars)
            self$.addOption(private$..ctrlvars)
            self$.addOption(private$..shwSig)
            self$.addOption(private$..flgSig)
            self$.addOption(private$..sidSig)
        }),
    active = list(
        corrvars = function() private$..corrvars$value,
        ctrlvars = function() private$..ctrlvars$value,
        shwSig = function() private$..shwSig$value,
        flgSig = function() private$..flgSig$value,
        sidSig = function() private$..sidSig$value),
    private = list(
        ..corrvars = NA,
        ..ctrlvars = NA,
        ..shwSig = NA,
        ..flgSig = NA,
        ..sidSig = NA)
)

partcorrResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        matrix = function() private$.items[["matrix"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Partial Correlation")
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="Partial Correlation Matrix",
                rows="(corrvars)",
                clearWith=list(
                    "shwSig",
                    "sidSig"),
                columns=list(
                    list(
                        `name`=".name[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`=".stat[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Pearson's r"),
                    list(
                        `name`=".name[rp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(shwSig)"),
                    list(
                        `name`=".stat[rp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="p-value", 
                        `visible`="(shwSig)"))))}))

partcorrBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "partcorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'PartialProximity',
                name = 'partcorr',
                version = c(1,0,0),
                options = options,
                results = partcorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Partial Correlation
#'
#' 
#' @param data .
#' @param corrvars .
#' @param ctrlvars .
#' @param shwSig .
#' @param flgSig .
#' @param sidSig .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$matrix} \tab \tab \tab \tab \tab Partial correlation matrix table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
partcorr <- function(
    data,
    corrvars,
    ctrlvars,
    shwSig = TRUE,
    flgSig = FALSE,
    sidSig = "twotailed") {

    if ( ! requireNamespace('jmvcore'))
        stop('partcorr requires jmvcore to be installed (restart may be required)')

    if ( ! missing(corrvars)) corrvars <- jmvcore::resolveQuo(jmvcore::enquo(corrvars))
    if ( ! missing(ctrlvars)) ctrlvars <- jmvcore::resolveQuo(jmvcore::enquo(ctrlvars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(corrvars), corrvars, NULL),
            `if`( ! missing(ctrlvars), ctrlvars, NULL))


    options <- partcorrOptions$new(
        corrvars = corrvars,
        ctrlvars = ctrlvars,
        shwSig = shwSig,
        flgSig = flgSig,
        sidSig = sidSig)

    analysis <- partcorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
